### ISSUE TITLE
make failed - incomplete typedef RSA

### ISSUE THREAD

**Issue by StakFallT** [giannitedesco/ccid-utils#1]
The subject of the issue entry is pretty self-explanatory. Here's what I did (including the errors)

Steps I used to get to the issue:
sh ./autogen.sh
./configure
make

Relevant section of output from make:

mv -f .deps/emv_data.Tpo .deps/emv_data.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include -I../include    -g -O2 -Wall -pipe -I/usr/include/libusb-1.0  -MT emv_sda.lo -MD -MP -MF .deps/emv_sda.Tpo -c -o emv_sda.lo emv_sda.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I../include -g -O2 -Wall -pipe -I/usr/include/libusb-1.0 -MT emv_sda.lo -MD -MP -MF .deps/emv_sda.Tpo -c emv_sda.c  -fPIC -DPIC -o .libs/emv_sda.o

emv_sda.c: In function ‘get_ca_key’:
emv_sda.c:91:12: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
   91 |         key->n = BN_bin2bn(modulus, mod_len, NULL);
      |            ^~
emv_sda.c:92:25: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
   92 |         if ( NULL == key->n )
      |                         ^~
emv_sda.c:95:12: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
   95 |         key->e = BN_bin2bn(exponent, exp_len, NULL);
      |            ^~
emv_sda.c:96:25: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
   96 |         if ( NULL == key->e )
      |                         ^~
emv_sda.c:103:20: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
  103 |         BN_free(key->n);
      |                    ^~

emv_sda.c: In function ‘make_issuer_pk’:
emv_sda.c:204:12: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
  204 |         key->n = BN_bin2bn(tmp, req->pk_cert_len, NULL);
      |            ^~
emv_sda.c:205:12: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
  205 |         key->e = BN_bin2bn(req->pk_exp, req->pk_exp_len, NULL);
      |            ^~
emv_sda.c:207:25: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
  207 |         if ( NULL == key->n || NULL == key->e ) {
      |                         ^~
emv_sda.c:207:43: error: invalid use of incomplete typedef ‘RSA’ {aka ‘struct rsa_st’}
  207 |         if ( NULL == key->n || NULL == key->e ) {
      |                                           ^~
make[1]: *** [Makefile:669: emv_sda.lo] Error 1
make[1]: Leaving directory '/home/stakfallt/GitHub/emv/ccid-utils/src'
make: *** [Makefile:453: all-recursive] Error 1

**Comment by giannitedesco** [comment]
Thanks. Looks like openssl made the internal fields of `struct RSA` private. Fixed this and another link error, too.
